name: Clean Old Sessions

on:
  schedule:
    - cron: '0 0 */7 * *' 
  workflow_dispatch: 

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Call Edge Function
        run: |
          curl -X POST "https://jywelkrjednvjsipeobo.supabase.co/functions/v1/ClearOldSessions" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_KEY }}"
